# Generated by Django 5.1.6 on 2025-02-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='darshanuser',
            name='confirm_password',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='darshanuser',
            name='password',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
