# Generated by Django 5.1.6 on 2025-02-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_darshanuser_confirm_password_darshanuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='darshanuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
