# Generated by Django 5.1.6 on 2025-02-20 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_darshanuser_groups_darshanuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='darshanuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='darshanuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='darshanuser',
            name='user_permissions',
        ),
    ]
