# Generated by Django 5.1.6 on 2025-02-20 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_darshanuser_groups_darshanuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DarshanType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('max_slots_per_time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('time_slot', models.CharField(max_length=20)),
                ('persons', models.IntegerField()),
                ('eca_person_name', models.CharField(max_length=255)),
                ('status', models.CharField(default='Booked', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('darshan_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.darshantype')),
            ],
        ),
        migrations.CreateModel(
            name='BookingMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('aadhar_number', models.CharField(max_length=12, unique=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='myapp.booking')),
            ],
        ),
    ]
