# Generated by Django 5.1.6 on 2025-02-20 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_darshantype_booking_bookingmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_range', models.CharField(max_length=50)),
                ('total_slots', models.IntegerField()),
                ('available_slots', models.IntegerField()),
                ('darshan_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='myapp.darshantype')),
            ],
        ),
    ]
