# Generated by Django 5.1.6 on 2025-02-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_booking_eca_person_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='time_range',
            field=models.CharField(max_length=20),
        ),
    ]
