# Generated by Django 5.1.6 on 2025-02-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_booking_time_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time_slot',
            field=models.CharField(max_length=50),
        ),
    ]
