# Generated by Django 5.1.6 on 2025-02-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_booking_time_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='time_range',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='new_time_range',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='eca_person_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time_slot',
            field=models.CharField(max_length=20),
        ),
    ]
