# Generated by Django 5.1.6 on 2025-02-22 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_booking_time_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='timeslot',
            name='slot_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.slotdate'),
        ),
    ]
