# Generated by Django 5.1.6 on 2025-02-22 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_slotdate_timeslot_slot_date_and_more'),
    ]

    operations = [
    ]
