# Generated by Django 5.1.6 on 2025-02-22 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_auto_20250222_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='slot_date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.slotdate'),
        ),
    ]
