# Generated by Django 5.1.6 on 2025-02-22 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_booking_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.ForeignKey(db_column='booking_date_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.slotdate'),
        ),
    ]
